### ISSUE TITLE
Generic Plugin

### ISSUE THREAD

**Issue by shyim** [1Password/shell-plugins#117]
### Platform or tool

Generic

### Relevant links

-

### Goal or desired behavior

When you built in your Company a custom tool and don't want to contribute it to this repo. It would make sense to have a basic generic plugin.

So my idea would be to have in the .config folder a yaml file something like

`.config/1password/tools/my_comany.yml`

```yaml
executeables:
 - my-company
 mapping:
    MY_SECRET_ENV: field.APIToken
locator:
    DOMAIN: fooo
```

Deploying these build go files is annoying for Companies. Also break when the SDK moves forward. I have to re-build my plugins from last week :)

### Contribution

- [ ] I'd be up for building the plugin myself.
