### ISSUE TITLE
EKS AWS Credentials + GUI Based Programs

### ISSUE THREAD

**Issue by bassrock** [1Password/shell-plugins#512]
### Platform or tool

AWS

### Desired or expected behavior

When using EKS with 1password and kubectl following setup here https://github.com/1Password/shell-plugins/issues/212#issuecomment-1733578472 I would expect to be able to use GUI programs that interact with Kubectl.

The programs I am using or [Lens](https://k8slens.dev/) or [Aptakube](https://aptakube.com/)

### Current behavior

Kubectl works perfectly on the terminal following the setup in https://github.com/1Password/shell-plugins/issues/212#issuecomment-1733578472.  However when Aptakube or Lens tries to interact with kubectl reading the configuration they error with something like the following after asking for my biopmetrics.

![Image](https://github.com/user-attachments/assets/0b211281-644e-48f6-8c60-3bb7d006b97e)

### Relevant log output

```shell

```

### op CLI version

2.30.0-beta.03

**Comment by alxmrtn** [comment]
Having a similar issue with JET Pilot as well - here's the user configuration in my kubeconfig:
```yaml
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1beta1
    command: op
    args:
    - plugin
    - run
    - --
    - aws
    - --region
    - us-east-1
    - eks
    - get-token
    - --cluster-name
    - foo
    - --output
    - json
    env: null
    interactiveMode: Always
    provideClusterInfo: false
```

My plugin is configured to only activate in `~/Development` - does it need to be set globally?
